name: Endure
main: net.thedudemc.endure.Endure
version: 0.1
author: jmilthedude
api-version: 1.14
commands:
  dude:
    description: Dude.
    usage: /dude
  get:
    description: Get.
    usage: /get <type> <name>